version: '3.8'
services:
  mysql_db:
    image: mysql
    container_name: mysql_db
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=db_capstone
    ports:
      - 3306:3306
    volumes:
      - mysql_db:/var/lib/mysql
    networks:
      - node-network
  app:
    depends_on:
      - mysql_db
    build: .
    container_name: cons-capstone-movie
    ports:
      - 8080:8080
    networks:
      - node-network
volumes:
  mysql_db:
    driver: local
networks:
  node-network:
